<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />

<?php
    require_once __DIR__.'/../inc/stdLib.php';
    $menu = $_SESSION['menu'];
    echo $menu['stylesheets'];
    echo $menu['javascripts'];
    echo $head['JQTABLE'];
    echo $head['THEME'];
?>


<script>
  $( document ).ready( function(){
    $( '#headline' ).html( 'Administration für LxCars - darf nur vom Profi benutzt werden.' );

    $( '#getKBAcars, #getKBAtrailer, #getKBAbike, #getKBAtruck, #getKBAtractor' ).button().click( function(){
      var name = $(this).attr('id');
      $.ajax({
        url: 'kba/getKBA.php',
        data: { 'action': name },
        success: function( rsp ){
          alert( name + ' Success!' );
        },
        error: function( rsp ){
          alert( 'Error ' + name + '!' );
        }
      })
    });

  });

</script>


</head>

<body>
<?php
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>

  <p id="headline" class="ui-state-highlight ui-corner-all tools" style="margin-top: 20px; padding: 0.6em;"></p>
  <div><button id="getKBAcars">Hole Auto KBA-Daten</button></div>
  <div><button id="getKBAtrailer">Hole Anhänger KBA-Daten</button></div>
  <div><button id="getKBAbike">Hole Motorad KBA-Daten</button></div>
  <div><button id="getKBAtruck">Hole Lkw KBA-Daten</button></div>
  <div><button id="getKBAtractor">Hole Zugmaschinen KBA-Daten</button></div>




<?php echo $menu['end_content']; ?>

</html>
