<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />

<?php
    require_once __DIR__.'/../inc/stdLib.php';
    $menu = $_SESSION['menu'];
    echo $menu['stylesheets'];
    echo $menu['javascripts'];
    //echo $head['JQTABLE'];
    echo $head['THEME'];
    echo $head['T8'];// Übersetzung mit kivi.t8
  ?>
<style>
    td{
      border-bottom-style: solid;
      border-bottom-color: #ffffff;
      border-bottom-width: 2px;

    }

    table .table1 {
      font-size: 14px;
      font-weight: bold;
    }

    .table1 td, .table1 th {
      text-align: left;
      padding: 2px;
      font-weight: bold;
      background-color: #eeeeee;
    }

    .table1 td:nth-child(even) {
      font-weight: normal;
      background-color: #ffffff;
    }

    table .sumTable {
      font-size: 14px;
      font-weight: bold;
      height: 40px;
    }


</style>

<script>
  $( document ).ready( function(){
    $( '#headline' ).html( kivi.t8( 'Fahrzeugschein-Scanner' ) );
    let fsmax = 16; //Wieviele Fahrzeugscheine sollen geholt werden
    $.ajax({
      url: 'ajax/fsscan.php',
      data: { action: 'getScans', data:{ 'fsmax': fsmax } },
      type: "POST",
      success: function( data ){
        console.log( data );
        var tableContent = '';
        data.forEach( function( item ){
          tableContent += '<tr class="line" id="' + item.id + '"><td style="text-align: right; padding-right: 15px;">' + item.dateFormatted + '</td><td>' + item.registrationNumber + '</td>';
        });
        $( '#tbody' ).empty().append( tableContent );
        //auf eine Zeile klicken und Daten des FS holen
        $( '#tbody tr' ).click( function(){
          //alert( this.id );
          $.ajax({
            url: 'ajax/fsscan.php',
            data: { action: 'getFsData', data:{ 'id': this.id  } },
            type: "POST",
            success: function( data ){
              console.log( data );
              alert( 'VIN: ' + data.vin + '\nHSN: ' + data.hsn + '\nTSN: ' + data.tsn );
            },
            error: function(){
              alert( 'getScans() Error');
            }
          })
        })//tr click
      },
      error: function(){
        alert( 'getFsData() Error');
      }
    })
  });

</script>

</head>

<body>
<?php
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>

  <p id="headline" class="ui-state-highlight ui-corner-all tools" style="margin-top: 20px; padding: 0.6em;"></p>
  <table id="dataTable" class="table1" >
    <col class="amounthead">
    <thead>
      <tr class="listheading">
        <th class="xlistheading" id="date">Datum</th>
        <th class="xlistheading" id="licenseplate">Kennzeichen</th>
      </tr>
    </thead>
    <tbody id="tbody" class="listrow">
    </tbody>
  </table>

<?php echo $menu['end_content']; ?>


</html>
