<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />
<?php
    require_once("../inc/stdLib.php");
    $menu = $_SESSION['menu'];
    $head = mkHeader();
    echo $menu['stylesheets'];
    echo $head['JTABLECSS'];
    echo $head['JQUERY'];   
    echo $head['JQUERYUI'];
    echo $head['THEME'];
    echo $head['JTABLEJS'];
    //print_r( $_SESSION );


?>
<script>

    $(document).ready(function(){
       // $( "#carlist" ).tablesorter({
            
        
        
        $.urlParam = function( name ){
            var results = new RegExp( '[\?&]' + name + '=([^&#]*)' ).exec( window.location.href );
            if( results == null ) alert( 'Parameter: "' + name + '" does not exist in "' + window.location.href + '"!' );               
            else return decodeURIComponent( results[1] || 0 );
        }
        //$.urlParam( 'param2' )
       $('#PersonTableContainer').jtable({
            title: 'Table of people',
            jqueryuiTheme: true,
            zebra: true,
            //paging: true,
            addRecordButton: false,
            sorting: true,
            defaultSorting: 'c_ln ASC',
            actions: {
                listAction: 'ajaxHelp/main.php?task=getCars',
                createAction: '/GettingStarted/CreatePerson',
                updateAction: '/GettingStarted/UpdatePerson',
                deleteAction: '/GettingStarted/DeletePerson'
            },
            fields: {
                c_ln: {
                    title: 'Kennzeichen',
                },
                herst: {
                    title: 'Hersteller',
                    width: '40%'
                },
                typ: {
                    title: 'Typ',
                    width: '20%'
                },
                name: {
                    title: 'Name'
                },
                art: {
                    title: 'Art',
                    width: '20%'
                },
                id: {
                    key: true,
                    create: false,
                    edit: false,
                    list: false
               }
            }
        });
        //alert( $.urlParam( 'task' ) );
        switch( $.urlParam( 'task' ) ) {
            case '1':
                //alert( 'tetst' );
                $.ajax({
                   // url: 'ajaxHelp/main.php',
                    //data: { task:  'getCars'  },
                    type: "POST",
                    success: function( json ) {
                        var obj = $.parseJSON( json.trim() )
                        //$( "#carlist" ).
                        //alert( json.toString());
                        $.each( obj, function( i, val ){
                           //alert( "Car" + val.c_ln ) 
                        });
                    }
                   
                });
                
 
        //Load student list from server
        //$('#carlist').jtable('load');
            break;
            case 2:
            //code block
            break;

        } 
     //$('#carlist').jtable('load');  
     $('#PersonTableContainer').jtable('load');
    });
</script>

<style>
    #example    { position:absolute; top:130px; left:87px; }
</style>
</head>
<body>
<?php 
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>
<div class="ui-widget-content" style="height:600px">

<div id="carlist"></div>
<div id="PersonTableContainer"></div>
            




</div>
<?php $menu['end_content']; ?>
</body>
</html>