<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />

<?php
    require_once( __DIR__."/../inc/stdLib.php" );
    $menu = $_SESSION['menu'];
    echo $menu['stylesheets'];
    echo $menu['javascripts'];
    echo $head['JQUERY'];
    echo $head['JQUERYUI'];
    echo $head['JQTABLE'];
    echo $head['THEME'];
    echo $head['JUI-DROPDOWN'];
    echo $head['TRANSLATION'];

/*************************************************************/
/************************ LxCars Auftrag *********************/
/************** ronny@lxcars.de, April 2010 ******************/
/*************************************************************/
//include_once( "../inc/stdLib.php" );
include_once("inc/lxcLib.php");
include_once("../inc/template.inc");
include_once("../inc/UserLib.php");
include_once ( "../inc/crmLib.php" );

ob_start();
$url = $_SERVER['SCRIPT_NAME'];
$s = $_GET["s"] ? $_GET["s"] : $_POST["s"];
?>


  <script type="text/javascript" src="autocomplete_customer.js"></script>
  <script type="text/javascript" src="autocomplete_part.js"></script>
  <script type="text/javascript" src="kivi.Order.js"></script>

<script>

$(document).ready(function() {

    $.urlParam = function( name ){
        var results = new RegExp( '[\?&]' + name + '=([^&#]*)' ).exec( window.location.href );
        if( results == null );// alert( 'Parameter: "' + name + '" does not exist in "' + window.location.href + '"!' );
        else return decodeURIComponent( results[1] || 0 );
    }
    
    /*****************************/
     /**************************/
      /***********************/
       /********************/
        /*****************/
                    
                    window.onbeforeunload = function() {
                        localStorage['dataObject'] = JSON.stringify(dataObject);
                    }
                    
                    window.onload = function() {
                        dataObject = JSON.parse(localStorage['dataObject']);
                        //console.log(dataObject);
                        $('#txtKennzeichen').val(dataObject['kennzeichen']);
                        $('#txtKundenname').val(dataObject['kundenname']);
                        $('#txtDatumVon').val(dataObject['datum_von']);
                        $('#txtDatumBis').val(dataObject['datum_bis']);
                        $('#txtStatus').val(dataObject['statusSearch']);
                        getOrderList();
                    }
    
    var kennzeichen;
    var kundenname;
    var datum_von;
    var datum_bis;
    var statusSearch = $('#txtStatus').val();
    var dataObject = {};
    
    $('button').button();
    
    $('#txtKennzeichen').on('keyup', function () {
        kennzeichen = $(this).val();
    })
    
    $('#txtKundenname').on('keyup', function () {
        kundenname = $(this).val();
    })
    
    $('#txtDatumVon').on('keyup', function () {
        datum_von = $(this).val();
    })
    
    $('#txtDatumBis').on('keyup', function () {
        datum_bis = $(this).val();
    })
    
    $('#txtStatus').change(function () {
    	statusSearch = $(this).val();
    	//console.log(statusSearch);
    })
    
    $('#btnSearch').click(function () {
        $('.showtableRow').remove();
        dataObject['kennzeichen'] = kennzeichen;
        dataObject['kundenname'] = kundenname;
        dataObject['datum_von'] = datum_von;
        dataObject['datum_bis'] = datum_bis;
        dataObject['statusSearch'] = statusSearch;
        //console.log(dataObject);
        getOrderList();
    })
    
    /*
    $('.tblSearchTxt').on('keyup', function () {
        $('#showtableTBody tr').show();
        $('#showtableTBody tr:not(:contains(' + $(this).val() + '))').hide();
    })
    */
    
    function getOrderList() {
        //if (statusSearch == 'alle') {
            $.ajax({
                url: 'ajax/order.php',
                data: { action: "getOrderList", data: dataObject },
                type: "GET",
                success: function (data) {
                    //console.log(data);
            
                    $.each(data, function (index, item) {
                        if (item.auftragsstatus == null) {
                        	item.auftragsstatus = '';
                        }
                        if (item.car_status == null) {
                        	item.car_status = '';
                        }else {
                        	item.car_status = ' / '+item.car_status;
                        }
                        $(  '<tr id="'+item.auftragsnummer+'" class="showtableRow">'+
                                '<td class="back">'+item.auftragsstatus + '' + item.car_status+'</td>'+
                                '<td>'+item.kennzeichen+'</td>'+
                                '<td>'+item.besitzer+'</td>'+
                                '<td>'+item.auftragsdatum+'</td>'+
                                '<td>'+item.ersteposition+'</td>'+
                                '<td>'+item.auftragsnummer+'</td>'+
                                '<td class="vals v1">'+item.owner+'</td>'+
                                '<td class="vals v2">'+item.c_id+'</td>'+
                            '</tr>'
                        ).appendTo('#showtableTBody');

                        $('.showtableRow').click(function () {
                            //console.log($(this).attr('id'));
                            window.location = 'order.phtml?id='+$(this).attr('id')+'&owner='+$(this).children('.v1').text()+'&c_id='+$(this).children('.v2').text()+'&url=<?php echo $url ?>';
                        })
    
                        $('.vals').hide();
                        
                        $('#showtable').trigger('update');
    
                    })
                    
                    $('#showtable tr').each( function () {
                        if (
                            $(this).children('.back').text() == '') {
                        	    $(this).children('.back').css({
                        	       backgroundColor: 'none'
                        	    })
                    	}else if (
                            $(this).children('.back').text() == 'angenommen / Auto hier' || 
                            $(this).children('.back').text() == 'angenommen / Sonstiges zur Reparatur gebracht' || 
                            $(this).children('.back').text() == 'angenommen / Bestellung') {
                        	    $(this).children('.back').css({
                        	       backgroundColor: 'yellow'
                        	    })
                    	}else if (
                            $(this).children('.back').text() == 'bearbeitet / Auto hier' || 
                            $(this).children('.back').text() == 'bearbeitet / Sonstiges zur Reparatur gebracht' || 
                            $(this).children('.back').text() == 'bearbeitet / Bestellung') {
                        	    $(this).children('.back').css({
                        	       backgroundColor: 'green'
                        	    })
                    	}else if (
                            $(this).children('.back').text() == 'angenommen / Auto nicht hier' ||
                            $(this).children('.back').text() == 'nicht abgerechnet / Auto nicht hier') {
                        	    $(this).children('.back').css({
                        	       backgroundColor: 'red'
                        	    })
                    	} else {
                        	    $(this).children('.back').css({
                        	       backgroundColor: 'lightgrey'
                        	    })
                    	}
                    } )
                    
                },
                error: function () {
                    alert('holen der Orderliste fehlgeschlagen');
                }
            })
        //}
    }
    
        /*****************/
       /********************/
      /***********************/
     /**************************/
    /*****************************/
    
}); //Ende $(document).ready()

</script>
<style>

#show { position: absolute;top: 100px;left: 350px; }
.tablesorter { width:auto; cursor:pointer; widgets: ['zebra']; sortList: [[0,0]];}
.tdLeft { text-align:right; }
.tblSearchTxt { width: 200px; }

#btnDelete { margin-left: 10px; }

</style>
</head>

<body>
<?php
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>

<?php echo $menu['end_content']; ?>

<p class="ui-state-highlight ui-corner-all tools" style="margin-top: 20px; padding: 0.6em;">Testfile</p>

    <table id="searchTable">
        <tr>
            <td class="tdLeft">
                Kennzeichen:
            </td>
            <td>
                <input type="text" id="txtKennzeichen" class="tblSearchTxt">
            </td>
        </tr>
        <tr>
            <td class="tdLeft">
                Kundenname:
            </td>
            <td>
                <input type="text" id="txtKundenname" class="tblSearchTxt">
            </td>
        </tr>
        <tr>
            <td class="tdLeft">
                Datum von:
            </td>
            <td>
                <input type="text" id="txtDatumVon" class="tblSearchTxt">
            </td>
        </tr>
        <tr>
            <td class="tdLeft">
                Datum bis:
            </td>
            <td>
                <input type="text" id="txtDatumBis" class="tblSearchTxt">
            </td>
        </tr>
        <tr>
            <td class="tdLeft">
                Status:
            </td>
            <td>
                <select id="txtStatus" class="tblSearchTxt">
                    <option value="alle">alle</option>
                    <option value="angenommen">angenommen</option>
                    <option value="bearbeitet">bearbeitet</option>
                    <option value="abgerechnet">abgerechnet</option>
                    <option value="nicht abgerechnet" selected="true">nicht abgerechnet</option>
                </select>
            </td>
        </tr>
        <tr>
            <td class="tdLeft">
            </td>
            <td>
                <button id="btnSearch">Suchen</button>
                <button id="btnDelete">Löschen</button>
            </td>
        </tr>
    </table>
    
    <div id="show">
        <table id="showtable" class="tablesorter">
            <thead>
                <tr>
                    <th>Status</th>
                    <th>Kennzeichen</th>
                    <th>Besitzer</th>
                    <th>Auftragsdatum</th>
                    <th>Erste Position</th>
                    <th>Auftrags-Nr.</th>
                </tr>
            </thead>
            <tbody id="showtableTBody">
            </tbody>
        </table>
        
        <?php    
        echo $head["JQTABLE-PAGER"];
        ?>
        
    </div>
</body>
</html>
