<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />

<?php
    require_once( __DIR__."/../inc/stdLib.php" );
    $menu = $_SESSION['menu'];
    echo $menu['stylesheets'];
    echo $menu['javascripts'];
    echo $head['JQUERY'];
    echo $head['JQUERYUI'];
    echo $head['JQTABLE'];
    echo $head['THEME'];
    echo $head['JUI-DROPDOWN'];
    echo $head['TRANSLATION'];

/*************************************************************/
/************************ LxCars Auftrag *********************/
/************** ronny@lxcars.de, April 2010 ******************/
/*************************************************************/
//include_once( "../inc/stdLib.php" );
include_once("inc/lxcLib.php");
//include_once("../inc/template.inc");
include_once("../inc/UserLib.php");
include_once ( "../inc/crmLib.php" );

ob_start();
$url = $_SERVER['SCRIPT_NAME'];
$s = $_GET["s"] ? $_GET["s"] : $_POST["s"];
?>


 <script type="text/javascript" src="jQueryAddOns/date-time-picker.js"></script>
 <script type="text/javascript" src="jQueryAddOns/german-date-time-picker.js"></script>
 <link rel="stylesheet" href="css/lxc.Order.css" type="text/css" title="Stylesheet">
 <script type="text/javascript" src="js/lxc.Order.js"></script>
 <script type="text/javascript" src="js/locale/de.js"></script>


<script>

$(document).ready(function() {

    $.urlParam = function( name ){
        var results = new RegExp( '[\?&]' + name + '=([^&#]*)' ).exec( window.location.href );
        if( results == null );// alert( 'Parameter: "' + name + '" does not exist in "' + window.location.href + '"!' );
        else return decodeURIComponent( results[1] || 0 );
    }

    //Filename of this script
    var url = window.location.pathname;
    var filename = url.substring( url.lastIndexOf( '/' ) + 1 );

    var c_hsn = $.urlParam( 'c_hsn' );
    var c_tsn = $.urlParam( 'c_tsn' );
    var license_plate;
    var customerName;
    var dateFrom;
    var dateTo;
    var statusSearch = $( '#txtStatus' ).val();
    var dataObject = {};

    $( 'button' ).button();

    $( '#autocomplete_License_plate' ).on('change', function () {
        license_plate = $( this ).val();
    })

    $( '#autocomplete_customer_name' ).on( 'change', function () {
        customerName = $( this ).val();
    })

    $( '#dateFrom' ).on( 'change', function () {
        dateFrom = $(this).val();
    })

    $( '#dateTo' ).on( 'change', function () {
        dateTo = $(this).val();

    })

    $( '#txtStatus' ).change(function () {
        statusSearch = $(this).val();

        $( '.showtableRow' ).remove();
        dataObject['license_plate'] = license_plate;
        dataObject['customerName'] = customerName;
        dataObject['dateFrom'] = dateFrom;
        dataObject['dateTo'] = dateTo;
        dataObject['statusSearch'] = statusSearch;
        //console.log(dataObject);
        getOrderList();

        //console.log(statusSearch);
    })



    $( '#btnSearch' ).click(function () {
        $( '.showtableRow' ).remove();
        dataObject['license_plate'] = license_plate;
        dataObject['customerName'] = customerName;
        dataObject['dateFrom'] = dateFrom;
        dataObject['dateTo'] = dateTo;
        dataObject['statusSearch'] = statusSearch;
        //console.log(dataObject);
        getOrderList();
    })

    function AddButton( input ){
    setTimeout( function(){


    }, 1 );
  }

    $( ".datePicker" ).datepicker({

    });


    var autocomplete_License_plate = [];

    var autocomplete_customer_name = [];

    $.ajax({
      url: 'ajax/order.php?action=getAutocompleteLicensePlates',
      type: 'GET',
      success: function (data) {

          for( i = 0; i < data.length; i++ ){
           autocomplete_License_plate.push( data[i].c_ln );
          }

      }

    })

    $.ajax({
      url: 'ajax/order.php?action=getAutocompleteCustomer',
      type: 'GET',
      success: function ( data ) {

          for( i = 0; i < data.length; i++ ) {
              autocomplete_customer_name.push( data[i].name );;
          }


      }
    })

    function getOrderList() {
        //if (statusSearch == 'alle') {
            $.ajax({
                url: 'ajax/order.php',
                data: { action: "getOrderList", data: dataObject },
                type: "POST",
                success: function (data) {
                    //console.log(data);

                    $.each(data, function (index, item) {
                        if (item.status == null) {
                            item.status = '';
                        }
                        if (item.car_status == null) {
                            item.car_status = '';
                        }else {
                            item.car_status = ' / '+item.car_status;
                        }

                        $( '<tr id="'+ item.id +'" owner = "' + item.customer_id + '" c_id = '+ item.c_id + '  class="showtableRow">' +

                                '<td>' + item.owner + '</td>' +
                                '<td>' + item.c_ln + '</td>' +
                                '<td>' + item.description + '</td>' +
                                '<td>' + item.car_manuf + '</td>' +
                                '<td>' + item.car_type + '</td>' +
                                '<td>' + item.transdate + '</td>' +
                                '<td>' + item.ordnumber + '</td>' +
                                '<td class="status_' + item.status + ' '+item.car_status + ' ">' + item.status + '' + item.car_status + '</td>'+

                            '</tr>'
                        ).appendTo('#showtableTBody');
                        if (item.internal_order){
                            $('tr#'+item.id).addClass("internalorder");
                        }

                        $( '.showtableRow' ).click( function () {
                            //console.log($(this).attr('id'));
                            window.location = 'order.phtml?id=' + $(this).attr( 'id' )+'&owner=' + $(this).attr( 'owner' ) + '&c_id=' + $(this).attr( 'c_id' ) + '&previous=' + filename + '&c_hsn=' + c_hsn + '&c_tsn=' + c_tsn;
                        })
                    })
                    $('.status_angenommen').css('background-color', 'yellow');
                    $('td:contains("angenommen / Bestellung")').css('background-color', 'LightSkyBlue');
                    $('.status_bearbeitet').css('background-color', 'green');
                    $('.status_nicht').css('background-color', 'lightgrey');
                    $( '.nicht' ).css( 'background-color', 'red' );
                    $( '.status_bearbeitet.nicht' ).css('background-color', 'grey');
                    $( '.vals' ).hide();
                    $( '#showtable' ).trigger( 'update' );
                }
            })
        //}
    }


      dataObject['license_plate'] = license_plate;
      dataObject['customerName'] = customerName;
      dataObject['dateFrom'] = dateFrom;
      dataObject['dateTo'] = dateTo;
      dataObject['statusSearch'] = statusSearch;
      getOrderList();




    $( "#autocomplete_License_plate" ).autocomplete({
      source: autocomplete_License_plate
    });

    $( "#autocomplete_customer_name" ).autocomplete({
      source: autocomplete_customer_name
    });

    $( "#btnDelete" ).click(function() {
       $( "#autocomplete_License_plate, #autocomplete_customer_name" ).val( "" );
       $( "#dateFrom, #dateTo" ).val( "" );
       $( "#statusSearch" ).val( 'alle' );

       license_plate = '';
       customerName = '';
       dateFrom = '';
       dateTo = '';


    });


}); //Ende $(document).ready()

</script>
<style>

#show { position: absolute;top: 100px;left: 350px; }
.tablesorter { width:auto; cursor:pointer; widgets: ['zebra']; sortList: [[0,0]];}
.tdLeft { text-align:right; }
.tblSearchTxt { width: 200px; }
tr.internalorder * { background-color: lightgrey; }

#btnDelete { margin-left: 10px; }
</style>
</head>

<body>
<?php
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>

<?php echo $menu['end_content']; ?>

<p class="ui-state-highlight ui-corner-all tools" style="margin-top: 20px; padding: 0.6em;">Testfile</p>

    <table id="searchTable">
        <tr>
            <td class="tdLeft">
                Kennzeichen:
            </td>
            <td>
                <input type="text" id="autocomplete_License_plate" class="tblSearchTxt ">
            </td>
        </tr>
        <tr>
            <td class="tdLeft">
                Kundenname:
            </td>
            <td>
                <input type="text" id="autocomplete_customer_name" class="tblSearchTxt">
            </td>
        </tr>
        <tr>
            <td class="tdLeft">
                Datum von:
            </td>
            <td>
                <input type="text" id="dateFrom" class="datePicker">
            </td>
        </tr>
        <tr>
            <td class="tdLeft">
                Datum bis:
            </td>
            <td>
                <input type="text" id="dateTo" class="datePicker">
            </td>
        </tr>
        <tr>
            <td class="tdLeft">
                Status:
            </td>
            <td>
                <select id="txtStatus" class="tblSearchTxt">
                    <option value="alle">alle</option>
                    <option value="angenommen">angenommen</option>
                    <option value="bearbeitet">bearbeitet</option>
                    <option value="abgerechnet">abgerechnet</option>
                    <option value="nicht abgerechnet" selected="true">nicht abgerechnet</option>
                </select>
            </td>
        </tr>
        <tr>
            <td class="tdLeft">
            </td>
            <td>
                <button id="btnSearch">Suchen</button>
                <button id="btnDelete">Löschen</button>
            </td>
        </tr>
    </table>

    <div id="show">
        <table id="showtable" class="tablesorter">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Kennzeichen</th>
                    <th>Erste Position</th>
                    <th>Hersteller</th>
                    <th>Fahrzeugtyp</th>
                    <th>Datum</th>
                    <th>Auftragsnummer</th>
                    <th>Status</th>

                </tr>
            </thead>
            <tbody id="showtableTBody">
            </tbody>
        </table>

        <?php
        echo $head["JQTABLE-PAGER"];
        ?>

    </div>
</body>



</html>
