<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />

<?php
    require_once("../inc/stdLib.php");
    $menu = $_SESSION['menu'];
    echo $menu['stylesheets'];
    echo $menu['javascripts'];
    echo $head['JQUERY'];
    echo $head['JQUERYUI'];
    echo $head['JQTABLE'];
    //echo $head['JQTABLE-PAGER'];
    echo $head['THEME'];
    //echo $head['JUI-DROPDOWN'];
    echo $head['TRANSLATION'];



ob_start();

$c_id = $_GET["c_id"] ? $_GET["c_id"] : $_POST["c_id"];
$owner = $_GET["owner"] ? $_GET["owner"] : $_POST["owner"];


?>


<script>


$(document).ready(function() {

    $.urlParam = function( name ){
        var results = new RegExp( '[\?&]' + name + '=([^&#]*)' ).exec( window.location.href );
        if( results == null ) alert( 'Parameter: "' + name + '" does not exist in "' + window.location.href + '"!' );
        else return decodeURIComponent( results[1] || 0 );
    }
    //var task  = $.urlParam( 'task'  );
    var owner = $.urlParam( 'owner' );
    var c_id  = $.urlParam( 'c_id'  ); //Car-Id

    var kivi_global = jQuery.parseJSON( kivi.myconfig.global_conf );

    //Filename of this script
    var url = window.location.pathname;
    var filename = url.substring( url.lastIndexOf( '/' ) + 1 );

    console.log('test');
    var language = kivi.myconfig.countrycode;
    $( ".lang" ).each( function(){
        var key = $( this ).attr( "data-lang" );
        if( $( this ).is( ":input" ) ) $( this ).attr( 'title',  typeof( langData[language][key] ) != 'undefined' ? langData[language][key] : 'LNG ERR'  );
        else $( this ).text( typeof( langData[language][key] ) != 'undefined' ? langData[language][key] : 'LNG ERR'  );
    });

    $("#showtable").tablesorter().tablesorterPager({
        container: $("#pager"),
        size: 9999
    });

    $('.showtableRow').click(function () {
        //console.log($(this).attr('id'));
        window.location = 'order.phtml?id=' + $(this).attr('id') + '&owner=' + owner + '&c_id=' + c_id + '&previous=' + filename + '&newOrder=0';
    })

    $('#btnNewOrder').button().click(function () {
      window.location = 'order.phtml?owner=' + owner + '&c_id=' + c_id + '&previous=' + filename + '&newOrder=1  ';
        /*
        $.ajax({
            url: 'ajax/order.php?action=newOrder',
            data: { action: 'newOrder', data: { owner_id: owner, car_id: c_id }},
            type: 'POST',
            success: function ( newOrderID ){
                window.location = 'order.phtml?id=' + newOrderID + '&owner=' + owner + '&c_id=' + c_id + '&previous=' + filename + '&newOrder=1  ';
            },
            error:  function(){ alert("Holen der Auftrags-Nr fehlgeschlagen!"); }
        })

        */
    });

    $('#btnBack').button().click(function () {
        window.location = 'lxcmain.php?task=3&owner=' + owner + '&c_id=' + c_id;
    });

});

</script>

<style>
 .ui-menu { width: 180px; }
 .tablesorter { width:auto; cursor:pointer; widgets: ['zebra']; sortList: [[0,0]];}

</style>
</head>

<body>
<?php
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>

<?php echo $menu['end_content']; ?>


 <p class="ui-state-highlight ui-corner-all tools lang" style="margin-top: 20px; padding: 0.6em;" data-lang="TESTFILE">Testfile</p>

<?php


    echo (' <table id="showtable" class="tablesorter">
                <thead>
                    <tr>
                        <th>Datum</th>
                        <th>Auftrags-Nr.</th>
                        <th>Erster Posten</th>
                        <th>Betrag</th>
                    </tr>
                </thead>
                <tbody>');


                //holt die order Infos und die Beschreibung der ersten Position aus der Datenbank

                $rs = $GLOBALS['dbh']->getALL("SELECT distinct on (ordnumber) * FROM
                                              (
                                                SELECT distinct on (oe.ordnumber) 'true'::BOOL AS instruction,oe.id, oe.transdate, oe.ordnumber, instructions.description, oe.amount FROM oe, instructions, parts WHERE oe.customer_id = ".$owner." AND instructions.trans_id = oe.id AND oe.c_id = ".$c_id." AND parts.id = instructions.parts_id UNION
                                                SELECT distinct on (oe.ordnumber)'false'::BOOL AS instruction,oe.id, oe.transdate, oe.ordnumber, orderitems.description, oe.amount FROM oe, orderitems, parts WHERE oe.customer_id = ".$owner." AND oe.c_id = ".$c_id." AND orderitems.trans_id = oe.id AND parts.id = orderitems.parts_id ORDER BY instruction DESC
                                              ) AS testTable ORDER BY ordnumber DESC;");


                //writeLog($rs);

                foreach ($rs as $value){
                    echo ('
                        <tr id="'.$value['id'].'" class="showtableRow">
                            <td>'.$value['transdate'].'</td>
                            <td>'.$value['ordnumber'].'</td>
                            <td>'.$value['description'].'</td>
                            <td align="right">'.number_format($value['amount'], 2, ',', '.').'</td>
                        </tr>');
                }
                echo (  '</tbody></table>'
                            .$head["JQTABLE-PAGER"].
                            '<input type="button" id="btnNewOrder" value="new Order">
                             <input type="button" id="btnBack" value="back">');



?>



</body>
</html>
