<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />

<?php
    require_once("../inc/stdLib.php");
    $menu = $_SESSION['menu'];
    echo $menu['stylesheets'];
    echo $menu['javascripts'];
    echo $head['JQUERY'];
    echo $head['JQUERYUI'];
    echo $head['JQTABLE'];
    echo $head['THEME'];
?>

<script>

  $(document).ready(function() {

    $.urlParam = function( name ){
        var results = new RegExp( '[\?&]' + name + '=([^&#]*)' ).exec( window.location.href );
        if( results == null ) alert( 'Parameter: "' + name + '" does not exist in "' + window.location.href + '"!' );
        else return decodeURIComponent( results[1] || 0 );
    }
    //var task  = $.urlParam( 'task'  );
    var owner = $.urlParam( 'owner' );
    var c_id  = $.urlParam( 'c_id'  ); //Car-Id
    var c_hsn = $.urlParam( 'c_hsn' );
    var c_tsn = $.urlParam( 'c_tsn' );

    //Filename of this script
    var url = window.location.pathname;
    var filename = url.substring( url.lastIndexOf( '/' ) + 1 );

    $( "#showtable" ).tablesorter().tablesorterPager({
        container: $("#pager"),
        size: 9999
    });

    $( '#main_body' ).on( 'click', '.showtableRow', function(){
        window.location = 'order.phtml?id=' + $( this ).parents( '.tableRow' ).attr( 'id' ) + '&owner=' + owner + '&c_id=' + c_id + '&previous=' + filename + '&newOrder=0' + '&c_hsn=' + c_hsn + '&c_tsn=' + c_tsn;
    })



    $( '#btnNewOrder' ).button().click( function(){
      window.location = 'order.phtml?owner=' + owner + '&c_id=' + c_id + '&previous=' + filename + '&newOrder=1' + '&c_hsn=' + c_hsn + '&c_tsn=' + c_tsn;

    });

    $( '#btnBack' ).button().click( function(){
        window.location = 'lxcmain.php?task=3&owner=' + owner + '&c_id=' + c_id + '&c_hsn=' + c_hsn + '&c_tsn=' + c_tsn;
    });

    $.ajax({
      url: 'ajax/orderList.php',
      data: { action: 'getOrderList', data: { owner: owner, c_id: c_id } },
      type: 'POST',
      success: function( data ){
        var tr;
        for( var i = 0; i < data.length; i++ ){
          tr = $( '<tr id="' + data[i].id + '" class="tableRow" />' );
          tr.append( "<td class='showtableRow'>" + data[i].itime + "</td>" );
          tr.append( "<td class='showtableRow'>" + data[i].mtime + "</td>" );
          tr.append( "<td class='showtableRow'>" + data[i].ordnumber + "</td>" );
          tr.append( "<td class='showtableRow'>" + data[i].description + "</td>" );
          tr.append( "<td class='showtableRow' align='right'>" + data[i].amount.toFixed(2).replace( '.', ',' ) + "</td>" ); //ToDo: Use numberFormat
          tr.append( "<td><input value='X'  class='delete' type='button'></td>" );
          $( 'table' ).append( tr );
        }
       $( 'table' ).trigger( 'updateAll' );

      }//,
      //error: function(){
      //  alert( 'Error in fuction getOrderList()!');
      //}
    }) //ajax


    $( '#main_body' ).on( 'click', '.delete', function(){
      var orderID = $( this ).parents( '.tableRow' ).attr( 'id' ) ;
      var row = $( this ).parents( '.tableRow' );
      $( "#confirmDialog" ).dialog({
        resizable: false,
        height: "auto",
        width: 400,
        modal: true,
        title: 'Delete Order!',
        open: function() {
          $( this ).html( 'Do you want to delete this order irretrievably?' );
        },
        buttons: [{
          text: "Delete Order",
          click: function(){
            $.ajax({
              url: 'ajax/order.php',
              data: { action: 'removeOrder', data: { orderID: orderID } },
              type: 'POST',
              success: function(){
                row.remove();
                $( 'table' ).trigger( 'updateAll' );
              },
              error: function(){
                alert( 'Error in fuction removeOrder()!' );
              }
            }) //ajax
            $( this ).dialog( "close" );
          } //click
        }, //button
        {
          text: "Cancel",
          click: function(){
            $( this ).dialog( "close" );
          }
        }]
      }); //dialog
    });

  });

</script>

<style>
 .ui-menu { width: 180px; }
 .tablesorter { width:auto; cursor:pointer; widgets: ['zebra']; sortList: [[0,0]]; }

</style>
</head>

<body id="main_body">
<?php
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>
  <div id="dialog-confirm">
  <p class="ui-state-highlight ui-corner-all tools" style="margin-top: 20px; padding: 0.6em;" > Orderlist</p>
  <table id="showtable" class="tablesorter">
    <thead>
      <tr>
        <th>Erstellt am</th>
        <th>Bearbeitet am</th>
        <th>Auftrags-Nr.</th>
        <th>Erster Posten</th>
        <th>Betrag</th>
        <th><input value="x"  class="x" type="button"></th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>

<?php //echo $head["JQTABLE-PAGER"]; ?>

  <p></p>
  <input type="button" id="btnNewOrder" value="Neuer Auftrag">
  <input type="button" id="btnBack" value="zurück">
  <div id="confirmDialog">

<?php echo $menu['end_content']; ?>

</body>
</html>
