<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />

<?php
    require_once( __DIR__."/../inc/stdLib.php" );
    $menu = $_SESSION['menu'];
    echo $menu['stylesheets'];
    echo $menu['javascripts'];
    echo $head['JQUERY'];
    echo $head['JQUERYUI'];
    //echo $head['JQTABLE'];
    echo $head['THEME'];

?>


  <script type="text/javascript" src="../../js/autocomplete_customer.js"></script>
  <script type="text/javascript" src="../../js/autocomplete_part.js"></script>
  <script type="text/javascript" src="../../js/kivi.Order.js"></script>
  
<script>

$(document).ready(function() {

    $.urlParam = function( name ){
        var results = new RegExp( '[\?&]' + name + '=([^&#]*)' ).exec( window.location.href );
        if( results == null ) alert( 'Parameter: "' + name + '" does not exist in "' + window.location.href + '"!' );
        else return decodeURIComponent( results[1] || 0 );
    }

    var id = $.urlParam( 'id' );
    var timer;
    var articleDescription;
    var grp_name;

    var kivi_global = jQuery.parseJSON( kivi.myconfig.global_conf );
    var baseUrl = kivi_global.baseurl;

    //console.log( baseUrl )
    //console.log(kivi_global)
    //console.log(kivi_global.erp_all_groups)

    //Einfügen beim Laden
        //$("#pos__" + mycnt ).off( 'change' ); //detaching changehandler
        //Container for inputs
        $('<span class="part_picker">' + 
        '<input type="hidden" class="add_item_input part_autocomplete partpicker_fat_set_item" id="add_item_parts_id" name="add_item.parts_id" value="">'+
        '<span class="ui-helper-hidden-accessible" aria-live="polite" role="status">'+
            '4 results are available, use up and down arrow keys to navigate.'+
        '</span>'+
        '<input style="width: 300px" class="add_item_input" type="text" id="add_item_parts_id_name" name="" value="">'+
        '</span>').appendTo('body');//.attr('id','NewId_' + cnt);

}); //Ende $(document).ready()

</script>
<style>

table.tablesorter { width:auto; cursor:pointer; }

    #head01 {position: absolute; top: 135px; left: 5px; font-size: 12px;}
    #head02 {position: absolute; top: 135px; left: 125px; font-size: 12px;}
    #head03 {position: absolute; top: 135px; left: 500px; font-size: 12px;}
    #head04 {position: absolute; top: 135px; left: 650px; font-size: 12px;}
    #head05 {position: absolute; top: 150px; left: 5px; font-size: 12px;}
    #head06 {position: absolute; top: 150px; left: 125px; font-size: 12px;}
    #head07 {position: absolute; top: 150px; left: 500px; font-size: 12px;}
    #head08 {position: absolute; top: 150px; left: 650px; font-size: 12px; width: 100px}
    #head09 {position: absolute; top: 165px; left: 5px; font-size: 12px;}
    #head10 {position: absolute; top: 165px; left: 125px; font-size: 12px;}
    #head11 {position: absolute; top: 165px; left: 500px; font-size: 12px;}
    #head12 {position: absolute; top: 165px; left: 650px; font-size: 12px;}
    #head13 {position: absolute; top: 180px; left: 500px; font-size: 12px;}
    #head14 {position: absolute; top: 180px; left: 650px; font-size: 12px;}
    #head15 {position: absolute; top: 200px; left: 5px; font-size: 12px;}
    #head16 {position: absolute; top: 200px; left: 125px; font-size: 12px;}
    #head17 {position: absolute; top: 200px; left: 500px; font-size: 12px;}
    #head18 {position: absolute; top: 200px; left: 650px; font-size: 12px;}
    #head19 {position: absolute; top: 150px; left: 770px; font-size: 12px;}
    #head20 {position: absolute; top: 150px; left: 870px; font-size: 12px;}

    #sortable, #head { list-style-type: none; margin: 0; padding: 0;padding-left: 2.5em; width: 1550px; }
    #sortable li, #head li { margin: 0 3px 3px 3px; font-size: 1.4em; height: 30px; }
    #sortable li span { position: absolute; margin-left: -1.3em; }
    #buttons { padding-left: 2.5em; padding-top: 1em;    }
    .btn { position: relative; left: 15px; }
    .lblPos1 {  position:relative; left: 43px;}
    .lblPos2 {  position:relative; left: 48px;}
    .lblPos3 {  position:relative; left: 53px;}
    .lblPos4 {  position:relative; left: 60px;}
    .lblPos5 {  position:relative; left: 65px;}
    .lblPos6 {  position:relative; left: 555px;}
    .lblPos7 {  position:relative; left: 570px;}
    .lblPos8 {  position:relative; left: 645px;}
    .lblPos9 {  position:relative; left: 710px;}
    .lblPos10 {  position:relative; left: 765px;}
    .lblPos11 { position: relative; left: 835px;}
    .mv {  position:relative; left: 5px; top: 3px;}
    .rmv {  position:relative; left: 10px; top: 3px;}
    .pos {  position:relative; left: 20px; width: 50px; text-align: right; background: none; border-style: none; pointer-events: none;}
    .itemNr {  position:relative; left: 23px; width: 65px;}
    .description {  position:relative; left: 28px; width: 570px;}
    .unity {  position:relative; left: 33px; width: 50px}
    .price {  position:relative; left: 40px; width: 100px; text-align: right;}
    .discount {  position:relative; left: 45px; width: 100px;text-align: right;}
    .total {  position:relative; left: 50px; width: 100px;text-align: right;}
    .mechanics {  position:relative; left: 55px; width: 140px;}
    .status { position: relative; left: 60px; width: 140px;}
    .posID { position: relative; left: 65px; font-size: 12px; }

</style>
</head>

<body>
<?php
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>

<?php echo $menu['end_content']; ?>

<p class="ui-state-highlight ui-corner-all tools" style="margin-top: 20px; padding: 0.6em;">Testfile</p>




</body>
</html>
