<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />

<?php
    require_once __DIR__.'/../inc/stdLib.php';
    $menu = $_SESSION['menu'];
    echo $menu['stylesheets'];
    echo $menu['javascripts'];
    echo $head['JQTABLE'];
    echo $head['THEME'];
?>


<script>
  $( document ).ready( function(){
    const today = new Date();
    const index = today.getMonth() == 12 ? 0 : today.getMonth() + 1 ;


    //$( '#headline' ).html( kivi.t8( 'Headline' ) );
    $( '#month' ).prop( 'selectedIndex', index );
    $( '#generate').button().click( function() {
      alert( $( '#month' )[0].selectedIndex + 1 );
    })

  });

</script>

<style>



</style>
</head>

<body>
<?php
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>

  <p id="headline" class="ui-state-highlight ui-corner-all tools" style="margin-top: 20px; padding: 0.6em;">Serienbrief Hauptuntersuchung</p>
  <div id="example" style="position:absolute">
    <form id="monthSelect" style="margin : 1em;">
      <select id="month">
        <option id="0">Januar</option>
        <option id=>Februar</option>
        <option>März</option>
        <option>April</option>
        <option>Mai</option>
        <option>Juni</option>
        <option>Juli</option>
        <option>August</option>
        <option>September</option>
        <option>Oktober</option>
        <option>November</option>
        <option>Deuember</option>
      </select>
    </form>

    <button style="margin : 1em;" id="generate">generieren</button>
  </div>


<?php echo $menu['end_content']; ?>

</html>
