<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />

<?php
    require_once __DIR__.'/../inc/stdLib.php';
    $menu = $_SESSION['menu'];
    echo $menu['stylesheets'];
    echo $menu['javascripts'];
    echo $head['JQTABLE'];
    echo $head['THEME'];
?>
<style>
.letter {
  margin: 1em;
}
</style>

<script>
  $( document ).ready( function(){
    mydate = new Date();
    mydate.setMonth( mydate.getMonth() + 1 );
    const month = mydate.getMonth();
    const year = mydate.getFullYear();
    //alert( 'month: ' + month + ' year: ' + year )

    var getData = function( month, year ){
      $.ajax({
        url: 'ajax/seriesletter.php',
        type: 'POST',
        data: { action: "getData", data: { 'month': month, 'year': year }},
        success: function( data ){

          //console.log( data );

          $( ".var" ).detach();
          $.each( data, function( i, item ){
            var bgcolor = i % 2 ? "#ddddff" : "#ddffdd"; // Zebra
            $('<tr class="var"  bgcolor="' + bgcolor + '">').append(
            '<td><input type="checkbox" id="' + item.c_id + '" checked="true"></td>',
            '<td>' + item.c_ln + '</td>',
            '<td>' + item.name + '</td>',
            '<td>' + item.street + '</td>',
            '<td>' + item.zipcode + '</td>',
            '<td>' + item.city + '</td>' ).appendTo( '#mytable' );
          });
        },
        error: function(){
          alert( 'Error in function getData() !' )
        }
      });

    }

    //$( '#headline' ).html( kivi.t8( 'Headline' ) );
    $( '#month' ).prop( 'selectedIndex', month ).prop('complete', function(){
      getData( $( '#month' )[0].selectedIndex, year );
    }).change( function(){
      getData( $( '#month' )[0].selectedIndex, year );
    })
    $( '#generate, #sendPIN' ).button().click( function(){
      //var id = $(this)[0].id;
      //var params = $( "#mytable :input" ).serialize();
      var selectedArray = $('input[type=checkbox]:checked').map( function(){ return  this.id }).get();
      var notSelectedArray = $('input[type=checkbox]:not(:checked)').map( function(){ return  this.id }).get();
      selectedArray.push( $(this)[0].id );
      selectedArray.push( $( '#month :selected' ).text() + '_' + year );
      $.ajax({
        url: 'ajax/seriesletter.php',
        type: 'POST',
        data: { action: "generatePdf", data: selectedArray },
        success: function( result ){
          //console.log( result );
          if( result !== 1 ) alert( result );
          if( result ) window.open( 'seriesLetter/' + $( '#month :selected' ).text() + '_' + year + '.pdf', 'name' );
        },
        error: function( result ){
          //console.log( result );
          alert( 'Error in function generatePdf() !' + result.responseText );
        }
      }).done( function(){ //update not selectec cars in lxc_cars
        if( notSelectedArray.length === 0 ){
          console.log( notSelectedArray );
          $.ajax({
            url: 'ajax/seriesletter.php',
            type: 'POST',
            data: { action: "updateNotSelectedCars", data: notSelectedArray },
            success: function( result ){
              console.log( result );

            },
            error: function( result ){
              //console.log( result );
              alert( 'Error in function updateNotSelectedCars() !' + result.responseText );
            }
          })//ajax
        }//if
      })
    })

  });

</script>


</head>

<body>
<?php
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>

  <p id="headline" class="ui-state-highlight ui-corner-all tools" style="margin-top: 20px; padding: 0.6em;">Serienbrief Hauptuntersuchung</p>
  <div style="position:absolute">
    <form id="monthSelect" class="letter">
      <select id="month">
        <option>Januar</option>
        <option>Februar</option>
        <option>März</option>
        <option>April</option>
        <option>Mai</option>
        <option>Juni</option>
        <option>Juli</option>
        <option>August</option>
        <option>September</option>
        <option>Oktober</option>
        <option>November</option>
        <option>Dezember</option>
      </select>
    </form>



    <table id="mytable" class="letter ui-widget">
      <thead class="ui-widget-header">
        <tr>
          <th>Auswahl</th>
          <th>Kennzeichen</th>
          <th>Name</th>
          <th>Straße</th>
          <th>PLZ</th>
          <th>Ort</th>
        </tr>
      </thead>
    </table>

    <button class="letter" id="generate">generieren</button>
    <button class="letter" id="sendPIN">mit PIN versenden</button>
  </div>


<?php echo $menu['end_content']; ?>

</html>
