<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title></title>

<?php
    require_once( __DIR__."/../inc/stdLib.php" );
    //$menu = $_SESSION['menu'];
    echo $menu['stylesheets'];
    echo $menu['javascripts'];
    echo $head['THEME'];

?>

  <script type="text/javascript" src="js/lxc.Part.js"></script>

</head>
<body>


<?php
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>
<p class="ui-state-highlight ui-corner-all tools" style="margin-top: 20px; padding: 0.6em;">Order</p>

<div>
  <table id="input_row_table_id">
    <tbody>
      <tr valign="top" class="listrow">
        <td><span class="part_picker"><input type="hidden" class="add_item_input part_autocomplete" name="add_item.parts_id" id="add_item_parts_id" value="" data-part-picker-data="{&quot;style&quot;:&quot;width: 300px&quot;,&quot;class&quot;:&quot;add_item_input&quot;,&quot;fat_set_item&quot;:1}"><input fat_set_item="1" type="text" style="width: 300px" id="add_item_parts_id_name" class="add_item_input" name="" value=""></span></td>
      </tr>
    </tbody>
  </table>
 </div>

<?php echo $menu['end_content']; ?>




</body>
</html>
  
  