<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title></title>

<?php
    require_once( __DIR__."/../inc/stdLib.php" );
    //$menu = $_SESSION['menu'];
    echo $menu['stylesheets'];
    echo $menu['javascripts'];
    echo $head['THEME'];

?>

<script type="text/javascript" src="jQueryAddOns/date-time-picker.js"></script>
  <script type="text/javascript" src="jQueryAddOns/german-date-time-picker.js"></script>
<link rel="stylesheet" href="order.css" type="text/css" title="Stylesheet">
  <script type="text/javascript" src="js/lxc.Part.js"></script>
  
   <script type="text/javascript" src="kivi.Order.js"></script>

</head>
<body>


<?php
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>
<p class="ui-state-highlight ui-corner-all tools" style="margin-top: 20px; padding: 0.6em;">Order</p>

<!--
<div>
  <table id="input_row_table_id">
    <tbody>
      <tr valign="top" class="listrow">
        <td><span class="part_picker"><input type="hidden" class="add_item_input part_autocomplete" name="add_item.parts_id" id="add_item_parts_id" value="" data-part-picker-data="{&quot;style&quot;:&quot;width: 300px&quot;,&quot;class&quot;:&quot;add_item_input&quot;,&quot;fat_set_item&quot;:1}"><input fat_set_item="1" type="text" style="width: 300px" id="add_item_parts_id_name" class="add_item_input" name="" value=""></span></td>
      </tr>
    </tbody>
  </table>
 </div>
-->

<div class="ui-widget-content">
  	<div id="tmp"></div>
    	<div>
        	<p class="tools ui-state-highlight ui-corner-all lang " style="margin-top: 20px; padding: 0.6em;" data-lang="HEADLINE">
               <label id="head01">Auftragsnummer:</label>
               <label id="head02">0000</label>
               <label id="head03">Auftraggeber:</label>
                <label id="head04"></label></br>
                <label id="head05">Fertigstellung:</label>
                <input id="head06" type="text">
                <label id="head07">KM-Stand:</label>
                <input id="head08" type="text"></br>
                <label id="head09">bearbeitet von:</label>
                <label id="head19">Amtl.-Kennz.:</label>
                <input id="head20" type="text"></br>
                <label id="head10"></label>
                <label id="head11">bearbeitet am:</label>
                <label id="head12"></label></br>
                <label id="head13">KfZ:</label>
                <select id="head14" type="text">
                    <option>Auto nicht hier</option>
                    <option selected="selected">Auto hier</option>
                    <option>Sonstiges zur Reparatur gebracht</option>
                    <option>Bestellung</option>
                </select></br>
                <label id="head15">erstellt am:</label>
                <label id="head16"></label>
                <label id="head17">Status:</label>
                <select id="head18" type="text">
                    <option></option>
                    <option>angenommen</option>
                    <option>bearbeitet</option>
                    <option selected="selected">abgerechnet</option>
                </select>
           	</p>
            <div>
                <button id="backToCRM"></button>
                <button id="backToOrderList"></button>
                <button id="backToCar"></button>
                <button id="printOrder"></button>
                <button id="pdfOrder"></button>
                <button id="testBtn"></button>
                <div>
              
         </div>
            
         <div id="test">
            <form id="myform">
            <ul id="sortable">
            </ul>
                        <li>
                           <label id="netto">Netto:</label>
                           <input name="pos_orderTotalNetto" value="0" type="text" id="orderTotalNetto" class="ui-widget-content ui-corner-all" autocomplete="off">
                        </li></br>
                         <li>
                           <label id="brutto">Brutto:</label>
                            <input name="pos_orderTotalBrutto" value="0" type="text" id="orderTotalBrutto" class="ui-widget-content ui-corner-all" autocomplete="off">
                        </li>            
                </form>
            </div>
            </div>

 <div>
  <table id="input_row_table_id">
    <thead>
      <tr class="listheading">
        <th class="listheading" nowrap >Ware </th>
        <th class="listheading" nowrap >Beschreibung </th>
        <th class="listheading" nowrap width="5" >Menge </th>
        <th class="listheading" nowrap width="15">Preis </th>
        <th class="listheading" nowrap width="5" >Rabatt </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr valign="top" class="listrow">
        <td><span class="part_picker"><input id="add_item_parts_id" type="hidden" class="add_item_input part_autocomplete" name="add_item.parts_id" value="" data-part-picker-data="{&quot;fat_set_item&quot;:1,&quot;class&quot;:&quot;add_item_input&quot;,&quot;style&quot;:&quot;width: 300px&quot;}"><input type="text" id="add_item_parts_id_name" fat_set_item="1" style="width: 300px" class="add_item_input" name="" value=""></span></td>
        <td><input value="" name="add_item.description" type="text" id="add_item_description" class="add_item_input"></td>
        <td>
          <input name="add_item.qty_as_number" value="" class="add_item_input numeric" size="5" id="add_item_qty_as_number" type="text">
          <input class="add_item_input" id="add_item_unit" type="hidden" name="add_item.unit" value="">
        </td>
        <td><input name="add_item.sellprice_as_number" value="" size="10" type="text" id="add_item_sellprice_as_number" class="add_item_input numeric"></td>
        <td><input name="add_item.discount_as_percent" value="" class="add_item_input numeric" type="text" size="5" id="add_item_discount_as_percent"></td>
        <td><input onclick="kivi.Order.add_item()" type="button" value="Artikel hinzufügen"></td>
      </tr>
    </tbody>
  </table>
 </div>

<table width="100%">
    <tr>
      <td>

        <div id="row_table_scroll_id" style="overflow-y: auto; height: 25vh">
          <table id="row_table_id" class="ui-sortable" width="100%">
            <thead>
              <tr class="listheading">
               
                <th class="listheading" nowrap width="3" >Position </th>
                <th class="listheading" style='text-align:center' nowrap width="1"><img src="image/updown.png" alt="Eintrag umsortieren"></th>
                <th class="listheading" style='text-align:center' nowrap width="1"><img src="image/close.png" alt="Position löschen"></th>
                <th id="partnumber_header_id"  class="listheading" nowrap width="15"><a href='#' onClick='javascript:kivi.Order.reorder_items("partnumber")'> Artikelnummer</a></th>
                <th id="partclass_header_id"   class="listheading" nowrap width="2">Typ</th>
                <th id="description_header_id" class="listheading" nowrap           ><a href='#' onClick='javascript:kivi.Order.reorder_items("description")'>Beschreibung</a></th>
                <th id="qty_header_id"         class="listheading" nowrap width="5" ><a href='#' onClick='javascript:kivi.Order.reorder_items("qty")'>        Menge</a></th>
                <th class="listheading" nowrap width="5" >Einheit </th>
             
                <th id="sellprice_header_id"   class="listheading" nowrap width="15" ><a href='#' onClick='javascript:kivi.Order.reorder_items("sellprice")'> Preis</a></th>
                <th id="discount_header_id"    class="listheading" nowrap width="15" ><a href='#' onClick='javascript:kivi.Order.reorder_items("discount")'>  Rabatt</a></th>
                <th class="listheading" nowrap width="10">Gesamt </th>
                <th class="listheading" nowrap width="5" >Mechaniker </th>
                 <th class="listheading" nowrap width="5" >Status </th>
              </tr>
            </thead>
            

        </table>
        </div>

      </td>
    </tr>

<script type="text/javascript">

$(document).ready(function() {


	var kivi_global = jQuery.parseJSON( kivi.myconfig.global_conf );
	var baseUrl = kivi_global.baseurl;


kivi.setup_formats({
    numbers: kivi.myconfig.numberformat,
    dates:   kivi.myconfig.dateformat
  });  









});




</script>






<?php echo $menu['end_content']; ?>




</body>
</html>
  
  