ALTER TABLE lxc_cars ADD COLUMN chk_c_ln BOOLEAN DEFAULT TRUE;
ALTER TABLE lxc_cars ADD COLUMN chk_c_2 BOOLEAN DEFAULT TRUE;
ALTER TABLE lxc_cars ADD COLUMN chk_c_3 BOOLEAN DEFAULT TRUE;
ALTER TABLE lxc_cars ADD COLUMN chk_c_em BOOLEAN DEFAULT TRUE;
ALTER TABLE lxc_cars ADD COLUMN chk_c_hu BOOLEAN DEFAULT TRUE;
ALTER TABLE lxc_cars ADD COLUMN chk_fin BOOLEAN DEFAULT TRUE;
INSERT INTO lxc_ver (version) VALUES ('1.4.3-1');

