/*
DROP TABLE IF EXISTS lxc_fs_scans; 

CREATE TABLE lxc_fs_scans(
	itime 				TIMESTAMP WITHOUT TIME ZONE DEFAULT ( NOW() AT TIME ZONE 'utc'),
	scan_detail_id 		TEXT UNIQUE,
	scan_id 			TEXT UNIQUE,
	ez 					TEXT,
	ez_string			TEXT,
	hsn					TEXT,
	tsn					TEXT,
	vsn					TEXT,
	field_2_2			TEXT,
	vin					TEXT,
	d3					TEXT,
	registrationNumber	TEXT,
	name1				TEXT,
	name2				TEXT,
	firstname			TEXT,
	address1			TEXT,
	address2			TEXT,
	j					TEXT,
	field_4				TEXT,
	field_3				TEXT,
	d1					TEXT,
	d2_1				TEXT,
	d2_2				TEXT,
	d2_3				TEXT,
	d2_4				TEXT,
	field_2				TEXT,
	field_5_1			TEXT,
	field_5_2			TEXT,
	v9					TEXT,
	field_14			TEXT,
	p3					TEXT,
	field_10			TEXT,
	field_14_1			TEXT,
	p1					TEXT,
	l					TEXT,
	field_9				TEXT,
	p2_p4				TEXT,
	t					TEXT,
	field_18			TEXT,
	field_19			TEXT,
	field_20			TEXT,
	g					TEXT,
	field_12			TEXT,
	field_13			TEXT,
	q					TEXT,
	v7					TEXT,
	f1					TEXT,
	f2					TEXT,
	field_7_1			TEXT,
	field_7_2			TEXT,
	field_7_3			TEXT,
	field_8_1			TEXT,
	field_8_2			TEXT,
	field_8_3			TEXT,
	u1					TEXT,
	u2					TEXT,
	u3					TEXT,
	o1					TEXT,
	o2					TEXT,
	s1					TEXT,
	s2					TEXT,
	field_15_1			TEXT,
	field_15_2			TEXT,
	field_15_3			TEXT,
	r					TEXT,
	field_11			TEXT,
	k					TEXT,
	field_6				TEXT,
	field_17			TEXT,
	field_16			TEXT,
	field_21			TEXT,
	field_22			TEXT,
	hu					TEXT,
	creation_date		TEXT,
	creation_city		TEXT,
	document_id			TEXT,
	maker				TEXT,
	model				TEXT,
	powerKw				TEXT,
	powerHpKw			TEXT,
	ccm					TEXT,
	fuel				TEXT,
	fuelCode			TEXT,
	filename			TEXT
);
--INSERT INTO  lxc_fs_scans  ( scan_detail_id, itime  )  VALUES ( 'jfoies488390', '2023-01-19 10:23:54'::TIMESTAMP );
--INSERT INTO  lxc_fs_scans  ( scan_detail_id, itime )  VALUES ( '646278337424468', '2023-01-20 08:53:24'::TIMESTAMP );

*/
--DELETE FROM lxc_fs_scans WHERE ez = '23.04.2001';
SELECT * FROM lxc_fs_scans;
--SELECT itime FROM lxc_fs_scans ORDER BY itime DESC;